 export var JOURNAL = [
    {"day": 1,"events":["paces round room when sun goes down","animal-like strength","redish nails", "rage in fullmoon"],"warewolf":true},
    {"day": 2,"events":["animal-like strength","redish nails","Has eyes the colour of the sun"],"warewolf":true},
    {"day": 3,"events":["rage in fullmoon","paces round room when sun goes down","Has a single, long eyebrow"],"warewolf":true},
    {"day": 4,"events":["brussel sprouts","ice cream","brushed teeth","computer","weekend"],"warewolf":false},
    {"day": 5,"events":["potatoes","candy","brushed teeth","exercise","weekend","dentist"],"warewolf":false},
    {"day": 6,"events":["brussel sprouts","pudding","brushed teeth","running","weekend"],"warewolf":false},
    {"day": 7,"events":["pizza","brushed teeth","computer","work","touched tree"],"warewolf":false},
    {"day": 8,"events":["bread","beer","brushed teeth","cycling","work"],"warewolf":false},
    {"day": 9,"events":["cauliflower","brushed teeth","work"],"warewolf":false},
    {"day": 10,"events":["pizza","brushed teeth","cycling","work"],"warewolf":false},
    {"day": 11,"events":["lasagna","nachos","brushed teeth","work"],"warewolf":false},
    {"day": 12,"events":["brushed teeth","weekend","touched tree"],"warewolf":false},
    {"day": 13,"events":["lettuce","brushed teeth","television","weekend"],"warewolf":false},
    {"day": 14,"events":["spaghetti","brushed teeth","work"],"warewolf":false},
    {"day": 15,"events":["brushed teeth","computer","work"],"warewolf":false},
    {"day": 16,"events":["lettuce","nachos","brushed teeth","work"],"warewolf":false},
    {"day": 17,"events":["carrot","brushed teeth","running","work"],"warewolf":false},
    {"day": 18,"events":["brushed teeth","work"],"warewolf":false},
    {"day": 19,"events":["cauliflower","reading","weekend"],"warewolf":false},
    {"day": 20,"events":["bread","brushed teeth","weekend"],"warewolf":false},
    {"day": 21,"events":["lasagna","brushed teeth","exercise","work"],"warewolf":false},
    {"day": 22,"events":["spaghetti","brushed teeth","reading","work"],"warewolf":false},
    {"day": 23,"events":["carrot","ice cream","brushed teeth","television","work"],"warewolf":false},
    {"day": 24,"events":["spaghetti","nachos","work"],"warewolf":false},
    {"day": 25,"events":["cauliflower","ice cream","brushed teeth","cycling","work"],"warewolf":false},
    {"day": 26,"events":["hate to be around wolfsbane","hate to be around objects made from silver"],"warewolf":true},
    {"day": 27,"events":["potatoes","ice cream","brushed teeth","computer","weekend"],"warewolf":false},
    {"day": 28,"events":["potatoes","ice cream","brushed teeth","work"],"warewolf":false},
    {"day": 29,"events":["peanuts","brushed teeth","running","work"],"warewolf":false},
    {"day": 30,"events":["potatoes","exercise","work"],"warewolf":false},
    {"day": 31,"events":["pizza","ice cream","computer","work"],"warewolf":false},
    {"day": 32,"events":["lasagna","ice cream","work"],"warewolf":false},
    {"day": 33,"events":["cauliflower","candy","reading","weekend"],"warewolf":false},
    {"day": 34,"events":["lasagna","nachos","brushed teeth","running","weekend"],"warewolf":false},
    {"day": 35,"events":["potatoes","brushed teeth","work"],"warewolf":false},
    {"day": 36,"events":["carrot","work"],"warewolf":false},
    {"day": 37,"events":["pizza","beer","work","dentist"],"warewolf":false},
    {"day": 38,"events":["lasagna","pudding","cycling","work"],"warewolf":false},
    {"day": 39,"events":["spaghetti","brushed teeth","reading","work"],"warewolf":false},
    {"day": 40,"events":["spaghetti","pudding","television","weekend"],"warewolf":false},
    {"day": 41,"events":["bread","brushed teeth","exercise","weekend"],"warewolf":false},
    {"day": 42,"events":["redish nails","rage in fullmoon"],"warewolf":true},
    {"day": 43,"events":["pizza","work"],"warewolf":false},
    {"day": 44,"events":["potatoes","exercise","work"],"warewolf":false},
    {"day": 45,"events":["brushed teeth","exercise","work"],"warewolf":false},
    {"day": 46,"events":["spaghetti","brushed teeth","television","work"],"warewolf":false},
    {"day": 47,"events":["pizza","cycling","weekend"],"warewolf":false},
    {"day": 48,"events":["carrot","brushed teeth","weekend"],"warewolf":false},
    {"day": 49,"events":["carrot","beer","brushed teeth","work"],"warewolf":false},
    {"day": 50,"events":["paces round room when sun goes down","animal-like strength"],"warewolf":true},
    {"day": 51,"events":["carrot","peanuts","brushed teeth","reading","work"],"warewolf":false},
    {"day": 52,"events":["potatoes","peanuts","brushed teeth","work"],"warewolf":false},
    {"day": 53,"events":["carrot","nachos","brushed teeth","exercise","work"],"warewolf":false},
    {"day": 54,"events":["pizza","peanuts","brushed teeth","television","weekend"],"warewolf":false},
    {"day": 55,"events":["lasagna","brushed teeth","cycling","weekend"],"warewolf":false},
    {"day": 56,"events":["cauliflower","peanuts","brushed teeth","computer","work","touched tree"],"warewolf":false},
    {"day": 57,"events":["lettuce","brushed teeth","television","work"],"warewolf":false},
    {"day": 58,"events":["potatoes","brushed teeth","computer","work"],"warewolf":false},
    {"day": 59,"events":["bread","candy","work"],"warewolf":false},
    {"day": 60,"events":["potatoes","nachos","work"],"warewolf":false},
    {"day": 61,"events":["carrot","pudding","brushed teeth","weekend"],"warewolf":false},
    {"day": 62,"events":["carrot","brushed teeth","exercise","weekend","touched tree"],"warewolf":false},
    {"day": 63,"events":["brussel sprouts","running","work"],"warewolf":false},
    {"day": 64,"events":["brushed teeth","work"],"warewolf":false},
    {"day": 65,"events":["lettuce","brushed teeth","running","work"],"warewolf":false},
    {"day": 66,"events":["candy","brushed teeth","work"],"warewolf":false},
    {"day": 67,"events":["brussel sprouts","brushed teeth","computer","work"],"warewolf":false},
    {"day": 68,"events":["bread","brushed teeth","weekend"],"warewolf":false},
    {"day": 69,"events":["cauliflower","brushed teeth","weekend"],"warewolf":false},
    {"day": 70,"events":["spaghetti","candy","television","work","touched tree"],"warewolf":false},
    {"day": 71,"events":["carrot","pudding","brushed teeth","work"],"warewolf":false},
    {"day": 72,"events":["lettuce","brushed teeth","work"],"warewolf":false},
    {"day": 73,"events":["carrot","ice cream","brushed teeth","cycling","work"],"warewolf":false},
    {"day": 74,"events":["pizza","brushed teeth","work"],"warewolf":false},
    {"day": 75,"events":["spaghetti","peanuts","exercise","weekend"],"warewolf":true},
    {"day": 76,"events":["bread","beer","computer","weekend","touched tree"],"warewolf":false},
    {"day": 77,"events":["brushed teeth","running","work"],"warewolf":false},
    {"day": 78,"events":["lettuce","peanuts","brushed teeth","work","touched tree"],"warewolf":false},
    {"day": 79,"events":["lasagna","brushed teeth","television","work"],"warewolf":false},
    {"day": 80,"events":["cauliflower","brushed teeth","running","work"],"warewolf":false},
    {"day": 81,"events":["carrot","brushed teeth","running","work"],"warewolf":false},
    {"day": 82,"events":["carrot","reading","weekend"],"warewolf":false},
    {"day": 83,"events":["paces round room when sun goes down","animal-like strength","redish nails"],"warewolf":true},
    {"day": 84,"events":["potatoes","brushed teeth","running","work"],"warewolf":false},
    {"day": 85,"events":["lasagna","ice cream","work","touched tree"],"warewolf":false},
    {"day": 86,"events":["cauliflower","peanuts","brushed teeth","cycling","work"],"warewolf":false},
    {"day": 87,"events":["pizza","brushed teeth","running","work"],"warewolf":false},
    {"day": 88,"events":["lettuce","brushed teeth","work"],"warewolf":false},
    {"day": 89,"events":["bread","brushed teeth","television","weekend"],"warewolf":false},
    {"day": 90,"events":["cauliflower","peanuts","brushed teeth","weekend"],"warewolf":false}
  ]; 
 